In [1]:
import numpy as np

In [3]:
a = [i for i in range(10)]

In [4]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
b = np.array(a)

In [6]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [8]:
b  = np.array(c)

In [9]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(b)

numpy.ndarray

In [11]:
b = np.array(a, dtype = float)

In [12]:
a = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9)

In [13]:
b = np.array(a, dtype = int)

In [14]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.array(a, dtype = float)

In [16]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [17]:
b = np.array(a, dtype = str)

In [18]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [19]:
a = ['abc', 1, 2, 3]

In [20]:
b = np.array(a)

In [22]:
b

array(['abc', '1', '2', '3'], dtype='<U3')

In [23]:
b.dtype

dtype('<U3')

In [24]:
b[0]

'abc'

In [25]:
b[1]

'1'

In [26]:
b.ndim

1

In [27]:
b.shape

(4,)

# 2D array

In [29]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
            [20, 21, 22, 23, 24, 25, 26, 27, 28, 29,]])

In [30]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
b.shape

(3, 10)

In [32]:
b.size

30

In [33]:
b[0][1]

1

In [34]:
b[2,5]

25

In [35]:
b[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [38]:
b[0:, 5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [39]:
c = b[1:, 4:]

In [40]:
c

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [41]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
c

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [43]:
c[1, 4] = 999

In [44]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27, 999,  29]])

In [47]:
b[1, 5] = 5555

In [48]:
c

array([[  14, 5555,   16,   17,   18,   19],
       [  24,   25,   26,   27,  999,   29]])

In [49]:
c

array([[  14, 5555,   16,   17,   18,   19],
       [  24,   25,   26,   27,  999,   29]])

In [50]:
c = b[1:, 5:].copy()

In [51]:
c

array([[5555,   16,   17,   18,   19],
       [  25,   26,   27,  999,   29]])

In [52]:
c[0, 0] = 777

In [53]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27, 999,  29]])

In [54]:
b

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12, 5555,   14, 5555,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,  999,   29]])

In [56]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27, 999,  29]])

#### Data types

In [59]:
b = np.array([1., 2., 3.], dtype = np.float32)

In [60]:
b

array([1., 2., 3.], dtype=float32)

In [61]:
b = np.array([1., 2., 3.], dtype = np.float64)

In [62]:
b

array([1., 2., 3.])

Опреации с векторами

In [63]:
a = np.array([0, 1, 2, 3, 4])

In [64]:
b = np.array([5, 6, 7, 8, 9])

In [65]:
a.size

5

In [66]:
b.size

5

In [67]:
a.shape

(5,)

In [68]:
b.shape

(5,)

Сложние векторов

In [69]:
c = a + b

In [70]:
c

array([ 5,  7,  9, 11, 13])

Сравним, что делает оператор "+" со списками в Python:

In [72]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [73]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Ещё 1 способ:

In [74]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

Вычитание векторов

In [76]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [77]:
d = a - b

In [78]:
d

array([ 2, -1,  1,  3,  0])

Альтернативный способ:

In [82]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

In [84]:
a.shape == b.shape

True

Умножение вектора на скаляр 

In [85]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [87]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [89]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [90]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

In [91]:
2 * [1, 2 , 3]

[1, 2, 3, 1, 2, 3]

Умножене массива на скаляр:

In [92]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [93]:
#Вариант №1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [94]:
#Вариант №2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [95]:
#Вариант №3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

Скалярное произведение векторов

In [96]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])   

In [97]:
a.shape

(3,)

In [98]:
b.shape

(3,)

In [99]:
a @ b

32

Операции с матрицами

In [101]:
A = np.array([[0, 1],
             [2, 3],
             [4, 5]])

In [102]:
B = np.array([[6, 7],
             [8, 9],
             [10, 11]])

In [103]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [104]:
C = np.add(A, B)

In [105]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Вычитание матриц

In [106]:
A = np.array([[6, 7],
             [8, 9],
             [10, 11]])

B = np.array([[0, 1],
             [2, 3],
             [4, 5]])

In [107]:
D = A - B
D

array([[6, 6],
       [6, 6],
       [6, 6]])

In [108]:
D = np.subtract(A, B)

In [109]:
D

array([[6, 6],
       [6, 6],
       [6, 6]])

In [110]:
X = D * 2
X

array([[12, 12],
       [12, 12],
       [12, 12]])

In [111]:
X = np.dot(D, 1022256454)
X

array([[6133538724, 6133538724],
       [6133538724, 6133538724],
       [6133538724, 6133538724]])

Умножение матриц

In [2]:
import numpy as np

In [3]:
X1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [4]:
X2 = np.array([[7, 8, 9, 10],
               [11, 12, 13, 14]])

Число столбцов первой матрицы должно ровняться числу строк второй матрицы

In [9]:
X1.shape[1] == X2.shape[0]

True

In [10]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [11]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [12]:
Z.shape

(3, 4)

Как получен элемент матрицы Z нулевой строки и нулевого столбца:

In [13]:
Z[0, 0]

29

In [14]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

Как получен элемент матрицы Z нулевой строки и первого столбца:

In [15]:
Z[0, 1]

32

In [17]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

32

Модуль Numpy linalg: Возведение матрицы в степень

In [19]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [20]:
a_square = np.dot(a, a)
a_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [23]:
a_square = np.linalg.matrix_power(a, 2)
a_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

Создание единичной матрицы

Единичная матрица - квадратная матрица с единицами по диагонали и нулями в остальных ячейках

In [26]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Умножение матрицы на единичную матрицу

In [27]:
A = np.array([[1, 2,],
              [3, 4,],
              [5, 6]])

Случай № 1

In [29]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [30]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Случай №2

In [31]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Транспонирование матрицы

In [33]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [34]:
at = a.transpose()
at

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Альтернативный вариант:

In [35]:
at = A.T

In [36]:
at

array([[1, 3, 5],
       [2, 4, 6]])

In [37]:
X = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [38]:
Y = np.array([[0, 1],
              [2, 3],
              [6, 7],
              [2, 5]])

In [39]:
Yt = Y.T
Yt

array([[0, 2, 6, 2],
       [1, 3, 7, 5]])

In [40]:
np.dot(X, Yt)

array([[ 2,  8, 20, 12],
       [ 4, 18, 46, 26],
       [ 6, 28, 72, 40]])

Вычисление определителя и ранга матрицы 

Пример №1

In [43]:
A = np.array([[0, 1 ,2],
             [3, 4, 5],
             [6, 7, 8]])

In [44]:
np.linalg.det(A)

0.0

In [45]:
np.linalg.matrix_rank(A)

2

Пример № 2

In [47]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [48]:
np.linalg.det(B)

85.99999999999997

In [49]:
np.linalg.matrix_rank(B)

3

Пример 3 (можно узнать только ранг матрицы, но не определитель, т.к. она не квадратная)

In [51]:
C  = np.array([[1, 2,],
               [3, 4],
               [5, 6]])

In [52]:
np.linalg.matrix_rank(C)

2

Вычисления обратной матрицы

In [54]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [55]:
B_inv = np.linalg.inv(B)

In [56]:
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [58]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

Автоматическое создание массивов

In [60]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

По умолчанию ряд начинается с 0,но можно явно задать начало последовательности.

In [63]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Последовательность с шагом 2:

In [64]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

в обратном порядке:

In [65]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

в обратном порядке с шагом 2:

In [67]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

Дробный шаг

In [68]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [69]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [71]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

Генерация случайных чисел

numpy.random.sample - случайные числа с равномерным распределением в промежутке (0,0 - 1,0)

Случайное число

In [72]:
np.random.sample()

0.524755635384385

Одномерный массив из 3 чисел:

In [74]:
np.random.sample(3)

array([0.95062919, 0.49174944, 0.62518453])

Двумерный массив 2 Х 3

In [75]:
np.random.sample((2, 3))

array([[0.67228586, 0.47852288, 0.68166143],
       [0.75394758, 0.47510142, 0.53840314]])

Массив 48х64х3 (например, это может быть случайное изображение с высотой 48 шириной 64 и значениями яркости трех цветов для каждого пикселя)

In [77]:
np.random.sample((48, 64, 3))

array([[[0.41754301, 0.89628269, 0.71685721],
        [0.62689292, 0.09071054, 0.72461074],
        [0.09948638, 0.13268551, 0.95064517],
        ...,
        [0.01244861, 0.43517331, 0.49134579],
        [0.02505932, 0.23197697, 0.7360837 ],
        [0.49878883, 0.47477687, 0.33371762]],

       [[0.54603237, 0.61165193, 0.74751499],
        [0.7342725 , 0.83644012, 0.02887797],
        [0.07416152, 0.12166335, 0.43671787],
        ...,
        [0.86042645, 0.87153957, 0.7864907 ],
        [0.14817139, 0.97841174, 0.91209269],
        [0.80188871, 0.1939021 , 0.69883165]],

       [[0.87601333, 0.49599644, 0.60578456],
        [0.59988517, 0.67168735, 0.48395064],
        [0.84269037, 0.58702132, 0.11901159],
        ...,
        [0.62556236, 0.33258338, 0.05250614],
        [0.34589377, 0.32938093, 0.60639727],
        [0.01768388, 0.54540611, 0.64947247]],

       ...,

       [[0.88966858, 0.39330396, 0.09197179],
        [0.95173519, 0.36411587, 0.49941804],
        [0.90959903, 0

numpy.random.randn - случайные числа с нормальным распределением

In [79]:
np.random.randn(10)

array([ 1.276928  , -0.20121856, -0.82847244, -1.34979188,  0.32474495,
       -1.41308879, -2.60906071,  1.3608294 , -0.87187471, -0.35977093])

In [80]:
np.random.randn(3, 4)

array([[ 0.97500713, -0.24383847,  1.0601797 , -0.60382586],
       [-0.85659966,  0.02747547,  0.5853818 ,  0.85315147],
       [-0.085882  ,  0.84962421, -0.04830474,  0.26583819]])

numpy.random.randint - массив из целых чисел

In [84]:
np.random.randint(0, 100, 10)

array([89, 88, 93, 38, 60, 25, 14, 55, 67, 28])

Двумерный массив 3х4

In [85]:
np.random.randint(0, 10, (3, 4))

array([[0, 7, 0, 6],
       [5, 5, 6, 1],
       [3, 4, 1, 1]])

numpy.random.choice - случайный выбор элементов

In [86]:
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [87]:
np.random.choice(b)

8

In [88]:
np.random.choice(b, 3)

array([5, 3, 8])

numpy.random.seed - инициализация генератора случайных чисел
Может использоваться для последующей воспроизводимости

In [90]:
np.random.seed(42)

In [91]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

Изменение формы  массива

In [92]:
a = np.arange(12)

In [93]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
np.reshape(a,(3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
np.reshape(a,(-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
a.resize(3, 4)

In [100]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Соединение массивов
Для наглядности возьмем два массива - с нулями и единицами:

In [105]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [106]:
b = np.ones((2, 3))

In [107]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

Соединение строк вертикально

In [108]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [112]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

Соединение столбцов (в горизонтальном измерении)

In [113]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [114]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [115]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение массивов в глубину (в третьем измерении)

In [116]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

Функции для работы с данными

Выбор данных

In [117]:
a = np.random.randint(0, 20, 10)
a

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [118]:
a[a > 10]

array([18, 11])

In [120]:
a[(a > 10) & (a % 2 == 0)] 

array([18])

In [121]:
a[(a > 10) | (a % 3 == 0)] 

array([ 6, 18,  3, 11])

numpy.where - первый вариант применения

In [122]:
a

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [125]:
np.where(a > 5)

(array([0, 1, 2, 3, 5, 8]),)

In [126]:
a[np.where(a > 10)]

array([18, 11])

numpy.where - второй вариант использования

In [128]:
a = [1, 4, 7]
b = [9, 2, 5]

In [131]:
np.where([True, False, True], a, b)

array([1, 2, 7])

Сортировка

In [132]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

In [133]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [134]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [135]:
a[:, 0].argsort()

array([0, 2, 1])

In [136]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

Случайное перемешивание массивов

In [137]:
a = np.arange(10)

In [138]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.random.shuffle(a)
a

array([5, 2, 7, 6, 8, 9, 3, 0, 4, 1])

Двумерные массивы

In [140]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [141]:
np.random.shuffle(a)

In [142]:
a

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 6,  7,  8]])

Математические действия с массивами

Применение математических функций ко всему массиву

In [143]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
# Логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [145]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [146]:
a.sum()

21

In [147]:
a.sum(axis = 0)

array([5, 7, 9])

In [148]:
a.sum(axis = 1)

array([ 6, 15])

In [149]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное умножение (не матричное)

In [151]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [153]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Broadcasting (сложение)

In [155]:
#1 й случай - совпадает только количество столбцов
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

In [157]:
b = np.array([1, 2])

In [158]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [159]:
#2й случай - совпадает только количество строк
c = np.array([[1],
             [2],
             [3]])


In [160]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

Статистические функции

In [161]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 9, 11, 11,  2],
       [11,  6,  3,  8],
       [ 2,  4,  2,  6]])

In [162]:
a.min()

2

In [163]:
#минимум для каждого столбца
a.min(axis = 0)

array([2, 4, 2, 2])

In [164]:
#максимум по каждой строке
a.max(axis = 1)

array([11, 11,  6])

In [165]:
#среднее для каждого столбца
a.mean(axis = 0)

array([7.33333333, 7.        , 5.33333333, 5.33333333])

In [166]:
# Среднее квадратичное отклонение
a.std(axis = 0)

array([3.8586123 , 2.94392029, 4.02768199, 2.49443826])

Запись и чтениие массива из файла

In [168]:
np.save('a.npy', a)

In [169]:
b = np.load('a.npy')

In [170]:
b

array([[ 9, 11, 11,  2],
       [11,  6,  3,  8],
       [ 2,  4,  2,  6]])